# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020, STMicroelectronics - All Rights Reserved
#

obj-$(CONFIG_USB_GADGET) += cmd_stm32prog.o
obj-y += stm32prog.o
obj-y += stm32prog_serial.o
obj-$(CONFIG_USB_GADGET) += stm32prog_usb.o
